#!/usr/bin/python3
##############################
 # @author [Wankun Deng]
 # @email [dengwankun@gmail.com]
 # @create date 2023-04-14 14:57:27
 # @modify date 2023-04-14 14:57:27
 # @desc [description]
#############################
import cgitb
import pandas as pd
import cgi
import json
import MySQLdb
cgitb.enable()
print( 'Content_Type:text/json; charset=utf-8\r\n\n')


form = cgi.FieldStorage()
cell=form['Cell'].value


## TODO : add the cell type information
des='Introduction of cell'
if cell=='Ex' or cell=='In':
    des='''
<div id="mw-content-text" class="mw-body-content mw-content-ltr" lang="en" dir="ltr"><div class="mw-parser-output">
<style data-mw-deduplicate="TemplateStyles:r1066479718">.mw-parser-output .infobox-subbox{padding:0;border:none;margin:-3px;width:auto;min-width:100%;font-size:100%;clear:none;float:none;background-color:transparent}.mw-parser-output 
    .infobox-3cols-child{margin:auto}.mw-parser-output .infobox .navbar{font-size:100%}body.skin-minerva .mw-parser-output .infobox-header,body.skin-minerva .mw-parser-output .infobox-subheader,body.skin-minerva .mw-parser-output 
    .infobox-above,body.skin-minerva .mw-parser-output .infobox-title,body.skin-minerva .mw-parser-output .infobox-image,body.skin-minerva .mw-parser-output .infobox-full-data,body.skin-minerva .mw-parser-output .infobox-below{text-align:center}</style>
<p>Within a <a href="/wiki/Nervous_system" title="Nervous system">nervous system</a>, a <b>neuron</b>, <b>neurone</b>, or <b>nerve cell</b> is an <a href="/wiki/Membrane_potential#Cell_excitability" title="Membrane potential">electrically excitable</a> <a href="/wiki/Cell_(biology)"
     title="Cell (biology)">cell</a> that fires electric signals called <a href="/wiki/Action_potentials" class="mw-redirect" title="Action potentials">action potentials</a>. Neurons communicate with other cells via <a href="/wiki/Synapse" 
     title="Synapse">synapses</a> - specialized connections that commonly use minute amounts of chemical <a href="/wiki/Neurotransmitter" title="Neurotransmitter">neurotransmitters</a> to pass the electric signal from the presynaptic neuron to the target cell through the synaptic gap. The neuron is the main component of <a href="/wiki/Nervous_tissue" title="Nervous tissue">nervous tissue</a> in all <a href="/wiki/Animalia" class="mw-redirect" title="Animalia">animals</a> except <a href="/wiki/Sponge" title="Sponge">sponges</a> and <a href="/wiki/Placozoa" title="Placozoa">placozoa</a>. Non-animals like <a href="/wiki/Plant" title="Plant">plants</a> and <a href="/wiki/Fungi" class="mw-redirect" title="Fungi">fungi</a> do not have nerve cells.
</p><p>Neurons are typically classified into three types based on their function. <a href="/wiki/Sensory_neuron" title="Sensory neuron">Sensory neurons</a> respond to <a href="/wiki/Stimulus_(physiology)" title="Stimulus (physiology)">stimuli</a> such as touch, sound, or light that affect the cells of the <a href="/wiki/Sense" title="Sense">sensory organs</a>, and they send signals to the spinal cord or brain. <a href="/wiki/Motor_neuron" title="Motor neuron">Motor neurons</a> receive signals from the brain and spinal cord to control everything from <a href="/wiki/Muscle_contraction" title="Muscle contraction">muscle contractions</a> to <a href="/wiki/Gland" title="Gland">glandular output</a>. <a href="/wiki/Interneuron" title="Interneuron">Interneurons</a> connect neurons to other neurons within the same region of the brain or spinal cord. When multiple neurons are functionally connected together, they form what is called a <a href="/wiki/Neural_circuit" title="Neural circuit">neural circuit</a>.
</p><p>A typical neuron consists of a cell body (<a href="/wiki/Soma_(biology)" title="Soma (biology)">soma</a>), <a href="/wiki/Dendrite" title="Dendrite">dendrites</a>, and a single <a href="/wiki/Axon" title="Axon">axon</a>. The soma is a compact structure, and the axon and dendrites are filaments extruding from the soma. Dendrites typically branch profusely and extend a few hundred micrometers from the soma. The axon leaves the soma at a swelling called the <a href="/wiki/Axon_hillock" title="Axon hillock">axon hillock</a> and travels for as far as 1 meter in humans or more in other species. It branches but usually maintains a constant diameter. At the farthest tip of the axon's branches are <a href="/wiki/Axon_terminals" class="mw-redirect" title="Axon terminals">axon terminals</a>, where the neuron can transmit a signal across the <a href="/wiki/Synapse" title="Synapse">synapse</a> to another cell. Neurons may lack dendrites or have no axon. The term <a href="/wiki/Neurite" title="Neurite">neurite</a> is used to describe either a dendrite or an axon, particularly when the cell is <a href="/wiki/Cellular_differentiation" title="Cellular differentiation">undifferentiated</a>.
</p><p>Most neurons receive signals via the dendrites and soma and send out signals down the axon. At the majority of synapses, signals cross from the axon of one neuron to a dendrite of another. However, synapses can connect an axon to another axon or a dendrite to another dendrite.
</p><p>The signaling process is partly electrical and partly chemical. Neurons are electrically excitable, due to maintenance of <a href="/wiki/Voltage" title="Voltage">voltage</a> gradients across their <a href="/wiki/Cell_membrane" title="Cell membrane">membranes</a>. If the voltage changes by a large enough amount over a short interval, the neuron generates an <a href="/wiki/All-or-none_law" title="All-or-none law">all-or-nothing</a> <a href="/wiki/Electrochemical" class="mw-redirect" title="Electrochemical">electrochemical</a> pulse called an <a href="/wiki/Action_potential" title="Action potential">action potential</a>. This potential travels rapidly along the axon and activates synaptic connections as it reaches them. Synaptic signals may be <a href="/wiki/Excitatory_postsynaptic_potential" title="Excitatory postsynaptic potential">excitatory</a> or <a href="/wiki/Inhibitory_postsynaptic_potential" title="Inhibitory postsynaptic potential">inhibitory</a>, increasing or reducing the net voltage that reaches the soma.
</p><p>In most cases, neurons are generated by <a href="/wiki/Neural_stem_cell" title="Neural stem cell">neural stem cells</a> during brain development and childhood. <a href="/wiki/Neurogenesis" title="Neurogenesis">Neurogenesis</a> largely ceases during adulthood in most areas of the brain.
</p>
</div><!--esi <esi:include src="/esitest-fa8a495983347898/content" /> --><noscript><img src="//en.wikipedia.org/wiki/Special:CentralAutoLogin/start?type=1x1" alt="" title="" width="1" height="1" style="border: none; position: absolute;" /></noscript>
</div>
This article uses material from the Wikipedia article <a href="https://en.wikipedia.org/wiki/Neuron">"Neuron"</a>, which is released under the <a href="https://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-Share-Alike License 3.0</a>.
<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1033289096">'''
if cell=='Mic':
    des='''
    <p><b>Microglia</b> are a type of <a href="/wiki/Neuroglia" class="mw-redirect" title="Neuroglia">neuroglia</a> (glial cell) located throughout the <a href="/wiki/Brain" title="Brain">brain</a> and <a href="/wiki/Spinal_cord" title="Spinal cord">spinal cord</a>.<sup id="cite_ref-1" class="reference"><a href="#cite_note-1">[1]</a></sup> Microglia account for about 10-15% of cells found within the brain.<sup id="cite_ref-2" class="reference"><a href="#cite_note-2">[2]</a></sup> As the resident <a href="/wiki/Macrophage" title="Macrophage">macrophage</a> cells, they act as the first and main form of active immune defense in the <a href="/wiki/Central_nervous_system" title="Central nervous system">central nervous system</a> (CNS).<sup id="cite_ref-Filiano_2015_3-0" class="reference"><a href="#cite_note-Filiano_2015-3">[3]</a></sup> Microglia (and other neuroglia including <a href="/wiki/Astrocytes" class="mw-redirect" title="Astrocytes">astrocytes</a>) are distributed in large non-overlapping regions throughout the CNS.<sup id="cite_ref-Kreutzberg_1995_4-0" class="reference"><a href="#cite_note-Kreutzberg_1995-4">[4]</a></sup><sup id="cite_ref-Bushong_2002_5-0" class="reference"><a href="#cite_note-Bushong_2002-5">[5]</a></sup> Microglia are key cells in overall brain maintenance—they are constantly scavenging the CNS for <a href="/wiki/Senile_plaques" class="mw-redirect" title="Senile plaques">plaques</a>, damaged or unnecessary <a href="/wiki/Neurons" class="mw-redirect" title="Neurons">neurons</a> and <a href="/wiki/Synapse" title="Synapse">synapses</a>, and infectious agents.<sup id="cite_ref-Gehrmann_1995_6-0" class="reference"><a href="#cite_note-Gehrmann_1995-6">[6]</a></sup> Since these processes must be efficient to prevent potentially fatal damage, microglia are extremely sensitive to even small pathological changes in the CNS.<sup id="cite_ref-Dissing-Olesen_2007_7-0" class="reference"><a href="#cite_note-Dissing-Olesen_2007-7">[7]</a></sup> This sensitivity is achieved in part by the presence of unique <a href="/wiki/Potassium_channels" class="mw-redirect" title="Potassium channels">potassium channels</a> that respond to even small changes in <a href="/wiki/Extracellular" class="mw-redirect" title="Extracellular">extracellular</a> potassium.<sup id="cite_ref-Gehrmann_1995_6-1" class="reference"><a href="#cite_note-Gehrmann_1995-6">[6]</a></sup> Recent evidence shows that microglia are also key players in the sustainment of normal brain functions under healthy conditions.<sup id="cite_ref-8" class="reference"><a href="#cite_note-8">[8]</a></sup> Microglia also constantly monitor neuronal functions through direct somatic contacts and exert neuroprotective effects when needed.<sup id="cite_ref-9" class="reference"><a href="#cite_note-9">[9]</a></sup>
</p>
<p>The brain and spinal cord, which make up the CNS, are not usually accessed directly by pathogenic factors in the body's circulation due to a series of <a href="/wiki/Endothelial_cells" class="mw-redirect" title="Endothelial cells">endothelial cells</a> known as the <a href="/wiki/Blood%E2%80%93brain_barrier" title="Blood–brain barrier">blood–brain barrier</a>, or BBB. The BBB prevents most infections from reaching the vulnerable nervous tissue. In the case where infectious agents are directly introduced to the brain or cross the blood–brain barrier, microglial cells must react quickly to decrease <a href="/wiki/Inflammation" title="Inflammation">inflammation</a> and destroy the infectious agents before they damage the sensitive neural tissue. Due to the lack of <a href="/wiki/Antibodies" class="mw-redirect" title="Antibodies">antibodies</a> from the rest of the body (few antibodies are small enough to cross the blood–brain barrier), microglia must be able to recognize foreign bodies, swallow them, and act as <a href="/wiki/Antigen-presenting_cell" title="Antigen-presenting cell">antigen-presenting cells</a> activating <a href="/wiki/T-cells" class="mw-redirect" title="T-cells">T-cells</a>.
</p>
This article uses material from the Wikipedia article <a href="https://en.wikipedia.org/wiki/Microglia">"Microglia"</a>, which is released under the <a href="https://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-Share-Alike License 3.0</a>.
<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1033289096">'''
elif cell=='Ast':
    des='''
<p><b>Astrocytes</b> (from <a href="/wiki/Ancient_Greek" title="Ancient Greek">Ancient Greek</a> <span title="Ancient Greek (to 1453)-language text"><span lang="grc"><a href="https://en.wiktionary.org/wiki/%E1%BC%84%CF%83%CF%84%CF%81%CE%BF%CE%BD" class="extiw" title="wikt:ἄστρον">ἄστρον</a></span></span>, <span title="Ancient Greek (to 1453)-language text"><i lang="grc-Latn">ástron</i></span>, "star" + <span title="Ancient Greek (to 1453)-language text"><span lang="grc"><a href="https://en.wiktionary.org/wiki/%CE%BA%CF%8D%CF%84%CE%BF%CF%82" class="extiw" title="wikt:κύτος">κύτος</a></span></span>, <span title="Ancient Greek (to 1453)-language text"><i lang="grc-Latn">kútos</i></span>, "cavity", "cell"), also known collectively as <b>astroglia</b>, are characteristic star-shaped <a href="/wiki/Glial_cells" class="mw-redirect" title="Glial cells">glial cells</a> in the <a href="/wiki/Brain" title="Brain">brain</a> and <a href="/wiki/Spinal_cord" title="Spinal cord">spinal cord</a>. They perform many functions, including biochemical control of <a href="/wiki/Endothelial_cell" class="mw-redirect" title="Endothelial cell">endothelial cells</a> that form the <a href="/wiki/Blood%E2%80%93brain_barrier" title="Blood–brain barrier">blood–brain barrier</a>,<sup id="cite_ref-Suzuki_Sa_Ochiai_Mullins_2014_pp._755–796_1-0" class="reference"><a href="#cite_note-Suzuki_Sa_Ochiai_Mullins_2014_pp._755–796-1">[1]</a></sup> provision of nutrients to the nervous tissue, maintenance of extracellular ion balance, regulation of cerebral blood flow, and a role in the repair and <a href="/wiki/Glial_scar" title="Glial scar">scarring</a> process of the brain and spinal cord following infection and traumatic injuries.<sup id="cite_ref-Freeman_2-0" class="reference"><a href="#cite_note-Freeman-2">[2]</a></sup> The proportion of astrocytes in the brain is not well defined; depending on the counting technique used, studies have found that the astrocyte proportion varies by region and ranges from 20% to around 40% of all glia.<sup id="cite_ref-3" class="reference"><a href="#cite_note-3">[3]</a></sup> Another study reports that astrocytes are the most numerous cell type in the brain.<sup id="cite_ref-Freeman_2-1" class="reference"><a href="#cite_note-Freeman-2">[2]</a></sup> Astrocytes are the major source of cholesterol in the central nervous system.<sup id="cite_ref-biorxiv.org_4-0" class="reference"><a href="#cite_note-biorxiv.org-4">[4]</a></sup> Apolipoprotein E transports cholesterol from astrocytes to neurons and other glial cells, regulating cell signaling in the brain.<sup id="cite_ref-biorxiv.org_4-1" class="reference"><a href="#cite_note-biorxiv.org-4">[4]</a></sup> Astrocytes in humans are more than twenty times larger than in rodent brains, and make contact with more than ten times the number of synapses.<sup id="cite_ref-Sloan_5-0" class="reference"><a href="#cite_note-Sloan-5">[5]</a></sup>
</p>
<p>Research since the mid-1990s has shown that astrocytes propagate intercellular <a href="/wiki/Calcium" title="Calcium">Ca<sup>2+</sup></a> waves over long distances in response to stimulation, and, similar to neurons, release transmitters (called <a href="/wiki/Gliotransmitter" title="Gliotransmitter">gliotransmitters</a>) in a Ca<sup>2+</sup>-dependent manner.<sup id="cite_ref-6" class="reference"><a href="#cite_note-6">[6]</a></sup> Data suggest that astrocytes also signal to neurons through Ca<sup>2+</sup>-dependent release of <a href="/wiki/Glutamate" class="mw-redirect" title="Glutamate">glutamate</a>.<sup id="cite_ref-pmid18834310_7-0" class="reference"><a href="#cite_note-pmid18834310-7">[7]</a></sup> Such discoveries have made astrocytes an important area of research within the field of <a href="/wiki/Neuroscience" title="Neuroscience">neuroscience</a>.
</p>
This article uses material from the Wikipedia article <a href="https://en.wikipedia.org/wiki/Astrocyte">"Astrocyte"</a>, which is released under the <a href="https://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-Share-Alike License 3.0</a>.
<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1033289096">'''
elif cell=='Oli':
    des='''
    <p><b>Oligodendrocytes</b> (from <a href="/wiki/Greek_language" title="Greek language">Greek</a>&nbsp;'<a href="/wiki/Cell_(biology)" title="Cell (biology)">cells</a> with a few branches'), or <b>oligodendroglia</b>, are a type of <a href="/wiki/Neuroglia" class="mw-redirect" title="Neuroglia">neuroglia</a> whose main functions are to provide support and insulation to <a href="/wiki/Axon" title="Axon">axons</a> in the <a href="/wiki/Central_nervous_system" title="Central nervous system">central nervous system</a> of <a href="/wiki/Jawed_vertebrates" class="mw-redirect" title="Jawed vertebrates">jawed vertebrates</a>, equivalent to the function performed by <a href="/wiki/Schwann_cell" title="Schwann cell">Schwann cells</a> in the <a href="/wiki/Peripheral_nervous_system" title="Peripheral nervous system">peripheral nervous system</a>. Oligodendrocytes do this by creating the <a href="/wiki/Myelin_sheath" class="mw-redirect" title="Myelin sheath">myelin sheath</a>.<sup id="cite_ref-CarlsonPhysiology_1-0" class="reference"><a href="#cite_note-CarlsonPhysiology-1">[1]</a></sup> A single oligodendrocyte can extend its processes to 50 axons,<sup id="cite_ref-2" class="reference"><a href="#cite_note-2">[2]</a></sup> wrapping approximately 1&nbsp;μm of myelin sheath around each axon; Schwann cells, on the other hand, can wrap around only one axon. Each oligodendrocyte forms one segment of myelin for several adjacent axons.<sup id="cite_ref-CarlsonPhysiology_1-1" class="reference"><a href="#cite_note-CarlsonPhysiology-1">[1]</a></sup>
</p>
<p>Oligodendrocytes are found only in the central nervous system, which comprises the <a href="/wiki/Brain" title="Brain">brain</a> and <a href="/wiki/Spinal_cord" title="Spinal cord">spinal cord</a>.  These cells were originally thought to have been produced in the <a href="/wiki/Neural_tube" title="Neural tube">ventral neural tube</a>; however, research now shows oligodendrocytes originate from the <a href="/wiki/Ventricular_zone" title="Ventricular zone">ventral ventricular zone</a> of the embryonic spinal cord and possibly have some concentrations in the forebrain.<sup id="cite_ref-3" class="reference"><a href="#cite_note-3">[3]</a></sup> They are the last cell type to be generated in the <a href="/wiki/Central_nervous_system" title="Central nervous system">central nervous system</a> (CNS).<sup id="cite_ref-4" class="reference"><a href="#cite_note-4">[4]</a></sup> Oligodendrocytes were discovered by <a href="/wiki/P%C3%ADo_del_R%C3%ADo_Hortega" title="Pío del Río Hortega">Pío del Río Hortega</a>.<sup id="cite_ref-5" class="reference"><a href="#cite_note-5">[5]</a></sup><sup id="cite_ref-6" class="reference"><a href="#cite_note-6">[6]</a></sup>
</p>
This article uses material from the Wikipedia article <a href="https://en.wikipedia.org/wiki/Oligodendrocyte">"Oligodendrocyte"</a>, which is released under the <a href="https://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-Share-Alike License 3.0</a>.
<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1033289096">'''
elif cell=='OPC':
    des='''<p><b>Oligodendrocyte progenitor cells</b> (<b>OPCs</b>), also known as <b>oligodendrocyte precursor cells</b>, <b>NG2-glia</b>, <b>O2A cells</b>, or <b>polydendrocytes</b>, are a subtype of <a href="/wiki/Neuroglia" class="mw-redirect" title="Neuroglia">glia</a> in the <a href="/wiki/Central_nervous_system" title="Central nervous system">central nervous system</a> named for their essential role as <a href="/wiki/Precursor_cell" title="Precursor cell">precursors</a> to <a href="/wiki/Oligodendrocytes" class="mw-redirect" title="Oligodendrocytes">oligodendrocytes</a>.<sup id="cite_ref-Nishiyama_2009_1-0" class="reference"><a href="#cite_note-Nishiyama_2009-1">[1]</a></sup> They are typically identified by co-expression of <a href="/wiki/PDGFRA" title="PDGFRA">PDGFRA</a> and <a href="/wiki/NG2_proteoglycan" title="NG2 proteoglycan">NG2</a>.<sup id="cite_ref-pmid29239330_2-0" class="reference"><a href="#cite_note-pmid29239330-2">[2]</a></sup>
</p>
<p>OPCs play a critical role in developmental and adult <a href="/wiki/Myelinogenesis" title="Myelinogenesis">myelinogenesis</a> by giving rise to oligodendrocytes, which then ensheath <a href="/wiki/Axon" title="Axon">axons</a> and provide electrical insulation in the form of a <a href="/wiki/Myelin" title="Myelin">myelin</a> sheath, enabling faster <a href="/wiki/Action_potential" title="Action potential">action potential</a> propagation and high fidelity transmission without a need for an increase in axonal diameter.<sup id="cite_ref-Swiss_2011_3-0" class="reference"><a href="#cite_note-Swiss_2011-3">[3]</a></sup> The loss or lack of OPCs, and consequent lack of differentiated oligodendrocytes, is associated with a loss of myelination and subsequent impairment of neurological functions.<sup id="cite_ref-doi_10.1002/glia.22406_4-0" class="reference"><a href="#cite_note-doi_10.1002/glia.22406-4">[4]</a></sup> In addition, OPCs express receptors for various <a href="/wiki/Neurotransmitters" class="mw-redirect" title="Neurotransmitters">neurotransmitters</a> and undergo membrane <a href="/wiki/Depolarization" title="Depolarization">depolarization</a> when they receive synaptic inputs from neurons.
</p>
This article uses material from the Wikipedia article <a href="https://en.wikipedia.org/wiki/Oligodendrocyte_progenitor_cell">"Oligodendrocyte progenitor cell"</a>, which is released under the <a href="https://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-Share-Alike License 3.0</a>.
<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1033289096">'''
elif cell=='End':
    des='''<p>The <b>endothelium</b> is a single layer of <a href="/wiki/Squamous_epithelial_cell" class="mw-redirect" title="Squamous epithelial cell">squamous</a> <b>endothelial cells</b> that line the interior surface of <a href="/wiki/Blood_vessel" title="Blood vessel">blood vessels</a> and <a href="/wiki/Lymphatic_vessel" title="Lymphatic vessel">lymphatic vessels</a>.<sup id="cite_ref-ReferenceA_1-0" class="reference"><a href="#cite_note-ReferenceA-1">[1]</a></sup> The endothelium forms an interface between circulating <a href="/wiki/Blood" title="Blood">blood</a> or <a href="/wiki/Lymph" title="Lymph">lymph</a> in the <a href="/wiki/Lumen_(anatomy)" title="Lumen (anatomy)">lumen</a> and the rest of the vessel wall. Endothelial cells form the barrier between vessels and tissue and control the flow of substances and fluid into and out of a tissue.
</p><p>Endothelial cells in direct contact with blood are called vascular endothelial cells whereas those in direct contact with <a href="/wiki/Lymph" title="Lymph">lymph</a> are known as lymphatic endothelial cells. Vascular endothelial cells line the entire <a href="/wiki/Circulatory_system" title="Circulatory system">circulatory system</a>, from the <a href="/wiki/Heart" title="Heart">heart</a> to the smallest <a href="/wiki/Capillaries" class="mw-redirect" title="Capillaries">capillaries</a>.
</p><p>These cells have unique functions that include <a href="/wiki/Ultrafiltration" title="Ultrafiltration">fluid filtration</a>, such as in the <a href="/wiki/Glomerulus" title="Glomerulus">glomerulus</a> of the kidney, <a href="/wiki/Muscle_tone" title="Muscle tone">blood vessel tone</a>, <a href="/wiki/Hemostasis" title="Hemostasis">hemostasis</a>, <a href="/wiki/Neutrophil" title="Neutrophil">neutrophil</a> recruitment, and hormone trafficking. Endothelium of the interior surfaces of the heart chambers is called <a href="/wiki/Endocardium" title="Endocardium">endocardium</a>. An impaired function can lead to serious health issues throughout the body.
</p>
This article uses material from the Wikipedia article <a href="https://en.wikipedia.org/wiki/Endothelium">"Endothelium"</a>, which is released under the <a href="https://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-Share-Alike License 3.0</a>.
<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1033289096">'''
elif cell=='BrainCell':
    des='''<p><b>Brain cells</b> make up the <a href="/wiki/Parenchyma#Brain" title="Parenchyma">functional tissue of the brain</a>. The rest of the brain tissue is structural or connective called the <a href="/wiki/Stroma_(tissue)" title="Stroma (tissue)">stroma</a> which includes <a href="/wiki/Blood_vessel" title="Blood vessel">blood vessels</a>. The two main types of cells in the <a href="/wiki/Brain" title="Brain">brain</a> are <a href="/wiki/Neuron" title="Neuron">neurons</a>, also known as nerve cells, and <a href="/wiki/Glial_cell" class="mw-redirect" title="Glial cell">glial cells</a> also known as neuroglia.<sup id="cite_ref-Purves_1-0" class="reference"><a href="#cite_note-Purves-1">[1]</a></sup> 
</p><p>Neurons are the <a href="/wiki/Excitable_cell" class="mw-redirect" title="Excitable cell">excitable cells</a> of the brain that function by communicating with other neurons and <a href="/wiki/Interneuron" title="Interneuron">interneurons</a> (via <a href="/wiki/Synapse" title="Synapse">synapses</a>), in <a href="/wiki/Neural_circuit" title="Neural circuit">neural circuits</a> and <a href="/wiki/Large-scale_brain_networks" class="mw-redirect" title="Large-scale brain networks">larger brain networks</a>. The two main neuronal classes in the <a href="/wiki/Cerebral_cortex" title="Cerebral cortex">cerebral cortex</a> are excitatory projection neurons, and inhibitory interneurons; around 70-80 per cent are neurons, and 20-30 per cent inhibitory interneurons.<sup id="cite_ref-Riedemann_2-0" class="reference"><a href="#cite_note-Riedemann-2">[2]</a></sup> Neurons are often grouped into a cluster known as a <a href="/wiki/Nucleus_(neuroanatomy)" title="Nucleus (neuroanatomy)">nucleus</a> where they usually have roughly similar connections and functions.<sup id="cite_ref-3" class="reference"><a href="#cite_note-3">[3]</a></sup> Nuclei are connected to other nuclei by <a href="/wiki/Nerve_tract" title="Nerve tract">tracts</a> of <a href="/wiki/White_matter" title="White matter">white matter</a>.
</p><p>Glia are the supporting cells of the neurons and have many functions not all of which are clearly understood, but include providing support and nutrients to the neurons. Glia are grouped into <a href="/wiki/Macroglia" class="mw-redirect" title="Macroglia">macroglia</a> of <a href="/wiki/Astrocyte" title="Astrocyte">astrocytes</a>, <a href="/wiki/Ependymal_cell" class="mw-redirect" title="Ependymal cell">ependymal cells</a>, and <a href="/wiki/Oligodendrocyte" title="Oligodendrocyte">oligodendrocytes</a>, and much smaller <a href="/wiki/Microglia" title="Microglia">microglia</a>. Astrocytes are seen to be capable of communication with neurons involving a signalling process similar to <a href="/wiki/Neurotransmission" title="Neurotransmission">neurotransmission</a> called <a href="/wiki/Gliotransmitter" title="Gliotransmitter">gliotransmission</a>.<sup id="cite_ref-Mederos_4-0" class="reference"><a href="#cite_note-Mederos-4">[4]</a></sup>
</p>
This article uses material from the Wikipedia article <a href="https://en.wikipedia.org/wiki/Brain_cell">"Brain cell"</a>, which is released under the <a href="https://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-Share-Alike License 3.0</a>.
<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1033289096">'''
elif cell=='RTE':
    des='''
    <p><b>Retrotransposons</b> (also called <b>Class I transposable elements</b> or <b>transposons via RNA intermediates</b>) are a type of
    genetic component that copy and paste themselves into different genomic locations (transposon) by converting RNA back into DNA through the reverse transcription
    process using an RNA transposition intermediate.
    <p>In scARE, we profiled RTE expression of <b>~850</b> subfamlies in over <b>600,000</b> cells, spanning <b>3</b> neurodegenerative diseases, including Alzheimer's disease, Parkinson's disease and multiple sclerosis.
    '''
elif cell=='AllDataset':
    des='''Summarization of all the dataset'''
print(des)